name: Eight Real
favicon: null
layout_spectrum: 0.65526
typography_spectrum: 0.5384
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#99cc00'
    - '#669966'
    - '#cc99ff'
    - '#656564'
  brandStrength: 0.9303550042677671
  lightness: 0.18647841666825116
  saturation: 0.4481953755021095
  rhythmicContrast: 0.7574905618093908
purpose: []
